commented out the Report to teams step

diff --git a/.github/workflows/gh-issues-to-azdo.yml b/.github/workflows/gh-issues-to-azdo.yml
--- a/.github/workflows/gh-issues-to-azdo.yml
+++ b/.github/workflows/gh-issues-to-azdo.yml
@@ -138,84 +138,84 @@ jobs:
             --data @patch-relation.json \
             "$WORK_ITEM_API_URL")
 
-      - name: Notify NI Developers on Teams
-        env:
-          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
-          ISSUE_TITLE: ${{ github.event.issue.title }}
-          ISSUE_BODY: ${{ github.event.issue.body }}
-          ISSUE_URL: ${{ github.event.issue.html_url }}
-          ISSUE_NUMBER: ${{ github.event.issue.number }}
-          WORK_ITEM_ID: ${{ steps.create-work-item.outputs.work_item_id }}
-          WORK_ITEM_URL: ${{ steps.create-work-item.outputs.work_item_url }}
-          WORK_ITEM_TYPE_ENCODED: ${{ steps.determine-work-item-type.outputs.result }}
-        run: |
-          echo "Decoding work item type..."
-          WORK_ITEM_TYPE=$(python -c "import urllib.parse; print(urllib.parse.unquote('''$WORK_ITEM_TYPE_ENCODED'''))")
+      # - name: Notify NI Developers on Teams
+      #   env:
+      #     TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
+      #     ISSUE_TITLE: ${{ github.event.issue.title }}
+      #     ISSUE_BODY: ${{ github.event.issue.body }}
+      #     ISSUE_URL: ${{ github.event.issue.html_url }}
+      #     ISSUE_NUMBER: ${{ github.event.issue.number }}
+      #     WORK_ITEM_ID: ${{ steps.create-work-item.outputs.work_item_id }}
+      #     WORK_ITEM_URL: ${{ steps.create-work-item.outputs.work_item_url }}
+      #     WORK_ITEM_TYPE_ENCODED: ${{ steps.determine-work-item-type.outputs.result }}
+      #   run: |
+      #     echo "Decoding work item type..."
+      #     WORK_ITEM_TYPE=$(python -c "import urllib.parse; print(urllib.parse.unquote('''$WORK_ITEM_TYPE_ENCODED'''))")
 
-          echo "Formatting issue body for Teams..."
-          FORMATTED_ISSUE_BODY=$(echo "$ISSUE_BODY" \
-            | sed -E 's/\*\*([^*]+)\*\*/<strong>\1<\/strong>/g' \
-            | sed ':a;N;$!ba;s/\n/<br>/g')
+      #     echo "Formatting issue body for Teams..."
+      #     FORMATTED_ISSUE_BODY=$(echo "$ISSUE_BODY" \
+      #       | sed -E 's/\*\*([^*]+)\*\*/<strong>\1<\/strong>/g' \
+      #       | sed ':a;N;$!ba;s/\n/<br>/g')
 
-          echo "Generating JSON payload with jq"
-          jq -n \
-            --arg issueTitle "$ISSUE_TITLE" \
-            --arg issueBody "$FORMATTED_ISSUE_BODY" \
-            --arg issueUrl "$ISSUE_URL" \
-            --arg issueNumber "$ISSUE_NUMBER" \
-            --arg workItemId "$WORK_ITEM_ID" \
-            --arg workItemType "$WORK_ITEM_TYPE" \
-            --arg workItemUrl "$WORK_ITEM_URL" \
-            '{
-              "@type": "MessageCard",
-              "@context": "https://schema.org/extensions",
-              "themeColor": "0076D7",
-              "summary": "New GitHub Issue and Work Item Created",
-              "sections": [
-                {
-                  "text": ("<strong>GitHub Issue:</strong> [#" + $issueNumber + " - " + $issueTitle + "](" + $issueUrl + ")<br><br>"
-                  + "<strong>AzDO Work Item ID:</strong> [" + $workItemId + "](" + $workItemUrl + ")<br>"
-                  + "<strong>AzDO Work Item Type:</strong> " + $workItemType + "<br><br>"
-                  + "<strong>Description:</strong> " + $issueBody),
-                  "markdown": true
-                }
-              ]
-            }' > teams_payload.json
+      #     echo "Generating JSON payload with jq"
+      #     jq -n \
+      #       --arg issueTitle "$ISSUE_TITLE" \
+      #       --arg issueBody "$FORMATTED_ISSUE_BODY" \
+      #       --arg issueUrl "$ISSUE_URL" \
+      #       --arg issueNumber "$ISSUE_NUMBER" \
+      #       --arg workItemId "$WORK_ITEM_ID" \
+      #       --arg workItemType "$WORK_ITEM_TYPE" \
+      #       --arg workItemUrl "$WORK_ITEM_URL" \
+      #       '{
+      #         "@type": "MessageCard",
+      #         "@context": "https://schema.org/extensions",
+      #         "themeColor": "0076D7",
+      #         "summary": "New GitHub Issue and Work Item Created",
+      #         "sections": [
+      #           {
+      #             "text": ("<strong>GitHub Issue:</strong> [#" + $issueNumber + " - " + $issueTitle + "](" + $issueUrl + ")<br><br>"
+      #             + "<strong>AzDO Work Item ID:</strong> [" + $workItemId + "](" + $workItemUrl + ")<br>"
+      #             + "<strong>AzDO Work Item Type:</strong> " + $workItemType + "<br><br>"
+      #             + "<strong>Description:</strong> " + $issueBody),
+      #             "markdown": true
+      #           }
+      #         ]
+      #       }' > teams_payload.json
 
-          echo "Previewing JSON payload:"
-          cat teams_payload.json
+      #     echo "Previewing JSON payload:"
+      #     cat teams_payload.json
 
-          echo "Sending notication to Teams Channel."
-          if ! curl -s -f -H "Content-Type: application/json" -d @teams_payload.json "$TEAMS_WEBHOOK_URL"; then
-            echo "Teams notification failed. Attempting to send error alert."
+      #     echo "Sending notication to Teams Channel."
+      #     if ! curl -s -f -H "Content-Type: application/json" -d @teams_payload.json "$TEAMS_WEBHOOK_URL"; then
+      #       echo "Teams notification failed. Attempting to send error alert."
 
-            jq -n \
-              --arg workItemId "$WORK_ITEM_ID" \
-              --arg workItemType "$WORK_ITEM_TYPE" \
-              --arg workItemUrl "$WORK_ITEM_URL" \
-              --arg issueUrl "$ISSUE_URL" \
-              --arg errorText "Unable to fetch the details for issue #$ISSUE_NUMBER" \
-              '{
-                "@type": "MessageCard",
-                "@context": "https://schema.org/extensions",
-                "themeColor": "FF0000",
-                "summary": "Unable to fetch Issue Details",
-                "sections": [
-                  {
-                    "text": ("<strong>Unable to fetch Issue Details</strong><br><br>"
-                    + "<strong>GitHub Issue:</strong> [View Issue](" + $issueUrl + ")<br>"
-                    + "<strong>AzDO Work Item ID:</strong> [" + $workItemId + "](" + $workItemUrl + ")<br>"
-                    + "<strong>AzDO Work Item Type:</strong> " + $workItemType + "<br><br>"
-                    + "<strong>Error Details:</strong> " + $errorText),
-                    "markdown": true
-                  }
-                ]
-              }' > teams_error_payload.json
+      #       jq -n \
+      #         --arg workItemId "$WORK_ITEM_ID" \
+      #         --arg workItemType "$WORK_ITEM_TYPE" \
+      #         --arg workItemUrl "$WORK_ITEM_URL" \
+      #         --arg issueUrl "$ISSUE_URL" \
+      #         --arg errorText "Unable to fetch the details for issue #$ISSUE_NUMBER" \
+      #         '{
+      #           "@type": "MessageCard",
+      #           "@context": "https://schema.org/extensions",
+      #           "themeColor": "FF0000",
+      #           "summary": "Unable to fetch Issue Details",
+      #           "sections": [
+      #             {
+      #               "text": ("<strong>Unable to fetch Issue Details</strong><br><br>"
+      #               + "<strong>GitHub Issue:</strong> [View Issue](" + $issueUrl + ")<br>"
+      #               + "<strong>AzDO Work Item ID:</strong> [" + $workItemId + "](" + $workItemUrl + ")<br>"
+      #               + "<strong>AzDO Work Item Type:</strong> " + $workItemType + "<br><br>"
+      #               + "<strong>Error Details:</strong> " + $errorText),
+      #               "markdown": true
+      #             }
+      #           ]
+      #         }' > teams_error_payload.json
 
-            echo "Sending fallback error card..."
-            curl -s -H "Content-Type: application/json" -d @teams_error_payload.json "$TEAMS_WEBHOOK_URL"
-            echo "Teams notification failed, continuing workflow..."
-          fi
+      #       echo "Sending fallback error card..."
+      #       curl -s -H "Content-Type: application/json" -d @teams_error_payload.json "$TEAMS_WEBHOOK_URL"
+      #       echo "Teams notification failed, continuing workflow..."
+      #     fi
 
       - name: Add comment on GitHub Issue
         uses: actions/github-script@v6
